import os

from onetick.py.otq import otq, _tmp_otq_path, otli, pyomd
from pandas import Timestamp as pd_Timestamp
from onetick.py.types import datetime as otp_datetime, datetime2expr
from datetime import datetime, date
from onetick.py import utils
from onetick.py.configuration import config
from onetick.py.log import get_debug_logger
from .query_parameters import _ExtendedQueryParameters


def is_datetime_type(dt):
    # TODO: move to types, add docs
    return isinstance(dt, (datetime, date, pd_Timestamp, otp_datetime, pyomd.timeval_t))


def is_millisecond_precision(dt):
    """
    dt can be a datetime object, a pd.Datetime object or an otp.dt object.
    We check if it has only millisecond precision or not.
    """
    if (dt.microsecond % 1000) != 0:
        return False
    if isinstance(dt, (pd_Timestamp, otp_datetime)):
        if dt.nanosecond != 0:
            return False
    return True


class TmpOtq:
    """
    Class that represents a storage of temporary queries
    """

    class __iter_str:
        """
        Class that produces unique strings
        """
        DEFAULT_LENGTH = 6
        FIRST_CODE = 97  # 'a'
        LAST_CODE = 122  # 'z'

        def __init__(self, length=None):
            if length is None:
                length = self.DEFAULT_LENGTH
            self.__length = length
            self.__n = 0

        def __num_to_str(self):
            s = ""
            r = self.LAST_CODE - self.FIRST_CODE + 1
            for i in range(0, self.__length):
                s = chr(self.FIRST_CODE + (self.__n // r ** i) % r) + s
            return s

        def get_str(self):
            s = self.__num_to_str()
            self.__n += 1
            return s

    name_generator = __iter_str()

    def __init__(self):
        self.queries: dict[str, tuple] = {}

    def add_query(self, query, suffix="", name=None, query_parameters: _ExtendedQueryParameters = None):
        """
        Adds query with a unique generated name to the storage.

        Parameters
        ----------
        query: otq.GraphQuery
            GraphQuery object that is being stored
        suffix: str
            Suffix that is added to the autogenerated string to form name of the query.
        name: str, optional
            If specified, this ``name`` will be used to save query
            and ``suffix`` parameter will be ignored.
        query_parameters: _ExtendedQueryParameters
            Can specify additional parameters with which this query will be saved to file.

        Returns
        -------
            result: str , name of the query in the file (without THIS:: prefix).
        """
        name = name or self.name_generator.get_str() + suffix
        if name in self.queries:
            raise ValueError(f"There is already a query with name '{name}' in {self.__class__.__name__} storage")
        query_parameters = query_parameters or _ExtendedQueryParameters()
        self.queries[name] = (query, query_parameters)
        return name

    def merge(self, tmp_otq: 'TmpOtq'):
        """
        Adds queries from the tmp_otq storage to the current storage.
        As query names are guaranteed to be unique session-wide, no check for collision is necessary.
        Queries with same names will always be the same.
        """
        self.queries.update(tmp_otq.queries)

    def copy(self):
        """
        Creates a copy of the storage
        """
        res = TmpOtq()
        res.merge(self)
        return res

    def _get_symbol_dates(self) -> list[str]:
        # check if any of the saved queries have symbol date set and return them (as strings in %Y%m%d format)
        return [
            utils.symbol_date_to_str(query_params.symbol_date)
            for _, query_params in self.queries.values()
        ]

    def save_to_file(
        self, query=None, query_name="main_query", file_path=None, file_suffix="",
        query_parameters: _ExtendedQueryParameters = None,
        default_query_parameters: _ExtendedQueryParameters = None,
    ):
        """
        Saves all queries from the query dict and one more query (if passed);
        returns absolute path to passed query in file (if passed) or path of resulted file

        Parameters
        ----------
        query: otq.GraphQuery or None
            Additional query that is saved with all the queries from the storage. Usually, this will be the main query
            of the Source object that uses this storage
        query_name: str
            Name with which additional query will be saved. As additional query is not stored in any TmpOtq object,
            it can be saved with a name that is specified completely and not generated to be unique
        file_path: str or None
            Path to the file where all queries will be saved. If None, a TmpFile will be created
        file_suffix: str
            Only used if file_path is None. A suffix that is added to the name of a generated file.
        query_parameters: _ExtendedQueryParameters
            Will be applied only to the query specified in the ``query`` parameter.
        default_query_parameters: _ExtendedQueryParameters
            Will be applied to all queries in the storage, but the values from ``query_parameters`` take precedence.

        Returns
        -------
            result: str , contains path to the resulting file with the name of the additional query
            (if "query" parameter is not None) or path to the resulting file otherwise

        """
        if file_path is None:
            base_dir = utils.default
            if os.getenv('OTP_WEBAPI_TEST_MODE'):
                base_dir = _tmp_otq_path()
            kwargs = {}
            if config.otq_debug_mode:
                kwargs['clean_up'] = False
            tmp_file = utils.TmpFile(suffix=file_suffix,
                                     base_dir=base_dir,
                                     **kwargs)
            file_path = tmp_file.path

        queries_dict = dict(self.queries)

        if query is not None:
            if query_name in self.queries.keys():
                query_name = self.name_generator.get_str() + "_" + query_name

            query_parameters = query_parameters or _ExtendedQueryParameters()
            queries_dict[query_name] = (query, query_parameters)

        default_query_parameters = default_query_parameters or _ExtendedQueryParameters()

        def time_interval_fix(qp: _ExtendedQueryParameters):
            # timezone definitions
            # in onetick and in dateutil can differ (e.g. "GMT-10" is +10:00 offset in onetick and -10:00 offset
            # in dateutil), therefore we always use time expressions to force onetick to make time conversions by itself
            # TODO: create a BDS ticket for the onetick team to fix it somehow
            if is_datetime_type(qp.start):
                if not qp.start_time_expression:
                    qp.start_time_expression = datetime2expr(qp.start)
                qp.start = None
            if is_datetime_type(qp.end):
                if not qp.end_time_expression:
                    qp.end_time_expression = datetime2expr(qp.end)
                qp.end = None


        # constructing a list of otq.Query objects, which will hold graphs, names, start/end times etc.
        query_list = []
        for stored_query_name, stored_query_tuple in queries_dict.items():
            stored_query = otq.Query(stored_query_tuple[0])
            stored_query_params: _ExtendedQueryParameters = stored_query_tuple[1]
            # default_query_parameters are overriden with specific values for each query
            stored_query_params = default_query_parameters.merge(stored_query_params)

            time_interval_fix(stored_query_params)

            if stored_query_params.timezone is not None:
                stored_query.set_timezone(stored_query_params.timezone)
            if stored_query_params.symbols is not None:
                stored_query.set_symbols(stored_query_params.symbols)
            stored_query.set_query_name(stored_query_name)
            if stored_query_params.start is not None:
                stored_query.set_start_time(stored_query_params.start)
            if stored_query_params.end is not None:
                stored_query.set_end_time(stored_query_params.end)
            if stored_query_params.start_time_expression:
                stored_query.set_start_time_expression(stored_query_params.start_time_expression)
            if stored_query_params.end_time_expression:
                stored_query.set_end_time_expression(stored_query_params.end_time_expression)

            if stored_query_params.running is not None:
                stored_query.set_running_query_flag(stored_query_params.running)
            if stored_query_params.symbol_date is not None:
                stored_symbol_date = int(utils.symbol_date_to_str(stored_query_params.symbol_date))
                stored_query.set_symbol_date(stored_symbol_date)
            if stored_query_params.concurrency is not None:
                stored_query.set_max_concurrency(stored_query_params.concurrency)
            if stored_query_params.batch_size is not None:
                stored_query.set_batch_size(stored_query_params.batch_size)
            if stored_query_params.query_properties is not None:
                stored_query.set_query_properties(
                    utils.query_properties_from_dict(stored_query_params.query_properties)
                )

            query_list.append(stored_query)

        _ = otli.OneTickLib()
        otq_file = otq.OtqFile(query_list)
        otq_file.save_to_file(file_path)
        get_debug_logger().debug(f'otq file saved to: {file_path}')

        if query is not None:
            return file_path + "::" + query_name
        else:
            return file_path
